# Generated by Django 4.2.7 on 2026-05-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("expiration_date", models.DateTimeField()),
                ("activated", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Prêmio",
                "verbose_name_plural": "Prêmios",
            },
        ),
        migrations.CreateModel(
            name="CarPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category_car",
                    models.CharField(
                        choices=[
                            ("economicos", "Econômicos"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=10,
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("activated", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ponto por carro",
                "verbose_name_plural": "Pontos por carros",
            },
        ),
        migrations.CreateModel(
            name="DaysPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("start_date", models.PositiveIntegerField(default=0)),
                ("end_date", models.PositiveIntegerField(default=0)),
                ("activated", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ponto por duração",
                "verbose_name_plural": "Pontos por duração",
            },
        ),
        migrations.CreateModel(
            name="DefaultPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type_points",
                    models.CharField(
                        choices=[
                            ("daily_points", "Pontos Diários"),
                            ("return_points", "Pontos por devolução"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Ponto Padrão",
                "verbose_name_plural": "Pontos Padrões",
            },
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_points", models.PositiveIntegerField(default=0)),
                ("end_points", models.PositiveIntegerField(default=0)),
                ("multiplier", models.FloatField()),
            ],
            options={
                "verbose_name": "Multiplicador de Nível",
                "verbose_name_plural": "Multiplicadores de Níveis",
            },
        ),
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("total_points", models.PositiveIntegerField(default=0)),
                ("points_to_next_tier", models.PositiveIntegerField(default=0)),
                ("lifetime_points_earned", models.PositiveIntegerField(default=0)),
                ("lifetime_points_redeemed", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Ponto do Usuário",
                "verbose_name_plural": "Pontos dos Usuários",
            },
        ),
        migrations.CreateModel(
            name="UserPointsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                (
                    "type_points",
                    models.CharField(
                        choices=[("earn", "Ganho"), ("redeem", "Resgate")],
                        max_length=10,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                ("gain", models.JSONField(blank=True, default=list, null=True)),
                (
                    "award",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido quando o tipo for resgate.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamifications.award",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de ponto do usuário",
                "verbose_name_plural": "Histórico de pontos dos usuários",
            },
        ),
    ]
