# Generated by Django 4.2.7 on 2026-05-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nivel",
            options={"verbose_name": "Nível", "verbose_name_plural": "Níveis"},
        ),
    ]
