# Generated by Django 4.2.7 on 2026-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamifications", "0003_alter_nivel_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportHistoricalPointsCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="gamificacao/relatorios/"
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "generated_successfully",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
            options={
                "verbose_name": "Exporta o histórico de ponto",
                "verbose_name_plural": "Exporta o histórico de pontos",
                "ordering": ["-id"],
            },
        ),
    ]
