# Generated by Django 4.2.7 on 2026-05-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamifications', '0004_exporthistoricalpointscsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporthistoricalpointscsv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gamifications/relatorios/'),
        ),
    ]
