# Generated by Django 4.2.7 on 2026-05-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_without_accents", models.CharField(max_length=180)),
                (
                    "alpha_code",
                    models.CharField(blank=True, max_length=3, null=True, unique=True),
                ),
                ("country_code", models.CharField(max_length=5, unique=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("sub_region", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("name_without_accents", models.CharField(max_length=180)),
                ("uf", models.CharField(max_length=2)),
                ("cod", models.PositiveIntegerField(default=1)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.country"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado às"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado às"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Deletado às"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deletado"
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("name_without_accents", models.CharField(max_length=180)),
                ("cod", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.state"
                    ),
                ),
            ],
            options={
                "verbose_name": "Município",
                "verbose_name_plural": "Municípios",
            },
        ),
    ]
